- docs/tutorial-basics/markdown-features.mdx
- docs/tutorial-react-native/_category_.json
- docs/tutorial-react-native/connecting.mdx
- docs/tutorial-react-native/installation.mdx
- docs/tutorial-react-native/list-other.mdx
- docs/tutorial-react-native/start-streaming.mdx
This PR will add first iteration of mobile SDK documentation
> Add first iteration of mobile docs

- .github/workflows/static_check.yml
- docusaurus.config.ts
Fixed broken links, add build check to CI
> Fix broken links, add build check to CI

- .gitignore
- .vscode/settings.json
- guide/integration.md
- guide/react-native/_category_.json
- guide/react-native/connecting.mdx
- guide/react-native/installation.mdx
- guide/react/_category_.json
- guide/server.mdx
Describe your changes in detail
> Fce 544/server sdk setup

- .github/workflows/static_check.yml
- .spelling
- guide/integration.md
- package.json
- yarn.lock
Introducing an automatic spellchecker.
Docusaurus already is scanning for broken links so we're already fine in this regard.
> Add spellchecker

- .spelling
> have one scope for spelling

- .spelling
- LICENSE
- README.md
> [FCE-592] Add Software Mansion to readme

- .spelling
- guide/index.md
- guide/react-native/installation.mdx
- Updated docs to work out of the box
> [FCE-576]: Update quick setup docs to use proper names

- guide/integration/index.md
FCE-597
Describe your changes in detail
> Fix formatting and slight improvements

- guide/integration/index.md
Followup to https://github.com/fishjam-cloud/documentation/pull/20
> [FCE-597] Fix typo and add link to server setup guide

- .github/workflows/docs.yaml
> yarn install with currently supported flags

- docs/production/server.mdx
Describe your changes in detail
> Update python server sdk docs

- docs/react/start-streaming.mdx
> Remove low-level api reference

- docs/react-native/quick-setup.md
> Fix RN quick setup sidebar position

- docs/react-native/connecting.mdx
- docs/react-native/quick-setup.md
Add info about `usePeerStatus` and formatting changes
> Update quick setup for RN

- .spelling
- docs/react-native/background.mdx
- docs/react-native/screensharing.mdx
- Updated docs to reflect current state of foreground service.
> [FCE-686]: Update docs to reflect current state

- docs/react/start-streaming.mdx
> Use `camera` instead of `devices` in React docs

- .spelling
- docs/production/examples/_category_.json
- docs/production/examples/fastapi.mdx
- docs/production/examples/fastify.mdx
- docs/production/server.mdx
Add examples of using Fishjam Server SDK in modern backend frameworks.
> FCE-797/add backend framework examples

- docs/react-native/background.mdx
- docs/react-native/connecting.mdx
- docs/react-native/quick-setup.md
- Improved warnings to be more visible 
- Fixed Fishjam URL syntax to be clearer.
> [FCE-851] Improve RN docs warnings and remove `*`

- .github/workflows/static_check.yml
- package.json
- yarn.lock
@dependabot is trying to bump docusaurus in few PRs, but it has to be done in single one. So here it is.
> Bump docusaurus from 3.6.0 to 3.6.3   

- docs/react-native/quick-setup.mdx
- docs/react-native/reconnect.mdx
- docs/react/connecting.mdx
- docs/react/installation.mdx
- docs/react/list-other.mdx
- docs/react/start-streaming.mdx
- docs/react/stream-middleware.mdx
- docs/react/toggling-devices.mdx
- Add documentation for `useConnection` hook on web.
- Fix how connection status is returned in mobile SDK.
- Unify code formatting with how it is done on mobile part.
> [FCE-931] Document useConnection on web

- .spelling
- docs/production/examples/fastify.mdx
- docs/react-native/_components/configure-permissions.mdx
- docs/react-native/background.mdx
- docs/react-native/screensharing.mdx
Small change that adds name of files in code blocks
(and some small fixes found during writing docs for metadata)
> Add filenames in sourcecode

- docs/react-native/quick-setup.mdx
- used `FishjamRoom` to simplify tldr example
> [FCE-906]: Make tldr example simpler

- docs/react/toggling-devices.mdx
Documentation update after merging FCE-960.
> update toggle docs

- docs/react/connecting.mdx
- docs/react/installation.mdx
- docs/react/list-other.mdx
- docs/react/start-streaming.mdx
- docs/react/stream-middleware.mdx
- docs/react/toggling-devices.mdx
> Add links to API in React docs

- docs/react-native/_components/configure-permissions.mdx
- docs/react-native/_components/install-package.mdx
- docs/react-native/connecting.mdx
- docs/react-native/installation.mdx
- docs/react-native/quick-setup.mdx
- package.json
- src/css/custom.css
As in the title, improves the quick start section.
> FCE-987 improve legibility of quick setup

- docs/glossary.md
- docs/react/managing-devices.mdx
- docs/react/toggling-devices.mdx
Add a paragraph about changing cameras and microphones.
> FCE-783/changing device docs

- .github/workflows/docs.yaml
- .github/workflows/static_check.yml
Update GH actions, as some of them are now deprecated
> [FCE-1126] Update GitHub Actions

- docs/production/server.mdx
Removes curl calls, updates the example url match current Fishjam spec.
> Remove curl calls

- docs/react-native/broadcasting.mdx
- Added a simple Broadcaster/Receiver example.
> FCE-1104: Add broadcasting documentation

- .spelling
- docs/audio-calls.mdx
- docs/production/_category_.json
- package.json
Closes FCE-1327
Adding basic documentation of what the benefits of using audio-only rooms are and how to use them.
> Add simple documentation of audio-only rooms

- docusaurus.config.ts
- package.json
- yarn.lock
> FCE-1246 / add search to docs

- docs/react/connecting.mdx
- docs/react/managing-devices.mdx
- docs/react/start-streaming.mdx
- docs/react/stream-middleware.mdx
Update snippets in react client
> FCE-1368/improve and fix snippets

- docs/react-native/quick-setup.mdx
- Fixed the example to reflect reality.
> FCE-1455: Improve minimal example react-native docs

- .spelling
- docs/react-native/custom-source.mdx
- Added basic custom source docs
> FCE-1442: Add docs how to use CustomSource

- .spelling
- docs/react-native/custom-video-sources/index.mdx
- docs/react-native/custom-video-sources/overview.mdx
- docs/react-native/custom-video-sources/vision-camera.mdx
- docusaurus.config.ts
- package.json
- yarn.lock
- More info on how to use our vision camera example.
- Moved custom sources docs into a common folder
> Add vision camera docs

- .spelling
- docs/react/custom-sources.mdx
Closes FCE-1496
Added documentation regarding custom sources in react-client
> Add custom sources documentation

- docs/livestreaming.mdx
> Update whep article link

- docs/tutorials/livestreaming.mdx
- versioned_docs/version-0.21.0/tutorials/livestreaming.mdx
- Updated docs to reflect current `LivestreamStreamer` mobile API.
> FCE-1868: Update Live streaming mobile docs

- docs/explanation/public-livestreams.mdx
- docs/tutorials/livestreaming.mdx
Describe your changes in detail
> Adjust imports for livestream module
